1
motocikljava/cookbook pull request #1
Opened 2023-02-15 16:06 UTC by motocikljava

2023-02-15 17:22 UTC, OlgaLugacheva requested changes

2023-02-15 17:22 UTC, OlgaLugacheva commented on src/main/java/model/Ingredient.java
> +public class Ingredient extends Recipe {
все-таки ингридиент не должен расширять рецепт

2023-02-15 17:22 UTC, OlgaLugacheva commented on src/main/java/services/impl/CookServiseIMPL.java
> +public class CookServiseIMPL {
а где контроллеры?

2023-02-21 07:47 UTC, OlgaLugacheva requested changes

2023-02-21 07:47 UTC, OlgaLugacheva commented on src/main/java/controllers/IngridientController.java
> +    @GetMapping("{ing}")
` @GetMapping("/{ing}")`

2023-02-21 07:47 UTC, OlgaLugacheva commented on src/main/java/controllers/RecipeController.java
> +    @GetMapping("{rec}")
@GetMapping("/{rec}")

2023-02-27 21:26 UTC, isavinov approved these changes

2023-03-20 18:00 UTC, merged